-- Create PRODUCT table
CREATE TABLE PRODUCT (
    PRODUCT_ID NUMBER(10) PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(30),
    PACKAGE_ID NUMBER(10),
    CURRENT_INVENTORY_COUNT NUMBER(5),
    STORE_COST NUMBER(10, 2),
    SALE_PRICE NUMBER(10, 2),
    LAST_UPDATE_DATE DATE,
    UPDATED_BY_USER VARCHAR2(30),
    PET_FLAG VARCHAR2(1)
);

-- Create PET_CARE_LOG table
CREATE TABLE PET_CARE_LOG (
    PRODUCT_ID NUMBER(10),
    LOG_DATETIME DATE,
    CREATED_BY_USER VARCHAR2(30),
    LOG_TEXT VARCHAR2(500),
    LAST_UPDATE_DATETIME DATE,
    PRIMARY KEY (PRODUCT_ID, LOG_DATETIME)
);

-- ADD RELATIONSHIP
ALTER TABLE PET_CARE_LOG
ADD CONSTRAINT fk_pet_log_product
FOREIGN KEY (PRODUCT_ID)
REFERENCES PRODUCT(PRODUCT_ID);

-- INSERT --
CREATE OR REPLACE TRIGGER trg_pet_log_bi
BEFORE INSERT ON PET_CARE_LOG
FOR EACH ROW
BEGIN
    :NEW.LAST_UPDATE_DATETIME := SYSDATE;
    :NEW.CREATED_BY_USER := USER;

EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20010, 'Insert error: ' || SQLERRM);
END;
/

-- UPDATE --
CREATE OR REPLACE TRIGGER trg_pet_log_bu
BEFORE UPDATE ON PET_CARE_LOG
FOR EACH ROW
BEGIN
    IF :OLD.CREATED_BY_USER != USER THEN
        RAISE_APPLICATION_ERROR(-20011, 'You can only update your own log');
    END IF;

    :NEW.LAST_UPDATE_DATETIME := SYSDATE;

EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20012, 'Update error: ' || SQLERRM);
END;
/

-- DELETE --
CREATE OR REPLACE TRIGGER trg_pet_log_bd
BEFORE DELETE ON PET_CARE_LOG
FOR EACH ROW
BEGIN
    IF USER != 'JOEMANAGER' THEN
        RAISE_APPLICATION_ERROR(-20013, 'Only JOEMANAGER can delete');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20014, 'Delete error: ' || SQLERRM);
END;
/

-- ONLY allow logs for pets --
CREATE OR REPLACE TRIGGER trg_pet_log_validate_pet
BEFORE INSERT ON PET_CARE_LOG
FOR EACH ROW
DECLARE
    v_pet_flag PRODUCT.PET_FLAG%TYPE;
BEGIN
    SELECT PET_FLAG
    INTO v_pet_flag
    FROM PRODUCT
    WHERE PRODUCT_ID = :NEW.PRODUCT_ID;

    IF v_pet_flag != 'Y' THEN
        RAISE_APPLICATION_ERROR(-20020, 'Cannot log non-pet product');
    END IF;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20021, 'Product does not exist');
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20022, 'Validation error: ' || SQLERRM);
END;
/


-- Test data --
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PET_FLAG)
VALUES (1, 'Dog', 'Y');

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PET_FLAG)
VALUES (2, 'Dog Food', 'N');

COMMIT;

-- Test INSERT --
INSERT INTO PET_CARE_LOG (PRODUCT_ID, LOG_DATETIME, LOG_TEXT)
VALUES (1, SYSDATE, 'Fed the dog');

-- ❌ Test INSERT for non-pet --
INSERT INTO PET_CARE_LOG (PRODUCT_ID, LOG_DATETIME, LOG_TEXT)
VALUES (2, SYSDATE, 'Fed the food');

-- UPDATE --
UPDATE PET_CARE_LOG
SET LOG_TEXT = 'Updated note'
WHERE PRODUCT_ID = 1;

-- ❌ Test DELETE (not manager) --
DELETE FROM PET_CARE_LOG WHERE PRODUCT_ID = 1;